version: '3'
services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${STORYLINK_USER}
            - POSTGRES_PASSWORD=${STORYLINK_PW}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:${PORT}:5432" 
    redis:
        image: redis:latest
        ports:
            - "127.0.0.1:6379:6379"
        command: redis-server --save ""

volumes:
    postgres-data:
        driver: local
