version: '3'
services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=storylink
            - POSTGRES_USER=${STORYLINK_USER}
            - POSTGRES_PASSWORD=${STORYLINK_PW}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:35000:1513" 

volumes:
    postgres-data:
        driver: local
